### PR TITLE
Add hidden background texture

### PR DESCRIPTION
**Pull request by OgelGames**
This adds a blank background texture to the statbar, so that texture packs can be used to override it, in the same way that the built-in health statbar works.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Textures are now added recursively. Moving it to `old` does not change anything.

**Comment by OgelGames** [comment]
Oh, I didn't know that, thanks for informing me 👍 

Should the old texture just be deleted then? Or...?

**Comment by SmallJoker** [comment]
Why not keep it where it was? Texture packs can override that anyway.

**Comment by OgelGames** [comment]
My intention was to add support for changing the background texture, without actually adding a background, so as not to change what players are already used to.

> Why not keep it where it was?

Because there can't be two textures with the same name...

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/025035db5c87e9eaa9f83859f860539fc4fb4dc0/src/client/hud.cpp#L613-L616

Seems like Minetest would generate a dummy texture if none is provided.

**Comment by OgelGames** [comment]
But there needs to be a texture for overriding to be possible... Right?

> This adds a blank background texture ... in the same way that the built-in health statbar works.

https://github.com/minetest/minetest/blob/025035db5c87e9eaa9f83859f860539fc4fb4dc0/builtin/game/statbars.lua#L4-L26

**Comment by SmallJoker** [comment]
Yes, that texture fallback is here: https://github.com/minetest/minetest/blob/master/textures/base/pack/heart_gone.png

I do not understand why `textures/stamina_hud_bg.png` is apparently removed in the PR; whereas it still exists in your PR branch (`master`).

**Comment by SmallJoker** [comment]
Sorry. I was once again bamboozled by the way how GitHub shows binary file modifications. I thought it was removed, rather than changed to a transparent texture.

**Review by SmallJoker — APPROVED** [review]
LGTM. Will merge in a few days if there are no objections.

**Comment by OgelGames** [comment]
@SmallJoker

**Pull request merged**
