### PR TITLE
use player attributes

### PR DESCRIPTION
**Pull request by sofar**
requires a dev release of minetest.

### CODE REVIEW

**Comment by sofar** [comment]
@bewlay 

This whole series looks quite good actually. It's quite messy in appearance, but I wouldn't have come to any different conclusion, really.

**Comment by sofar** [comment]
4efa141

**Comment by sofar** [comment]
merged - thanks a ton!

**Comment by sofar** [comment]
Note, I just discovered a bug in this and it broke the mod. Next time, please verify with luacheck that the code actually works!

**Comment by bewlay** [comment]
I'm quite new to lua, so I wasn't aware of luacheck. I will use it in the future, thanks!
Still, I just looked through the latest commits to see what I did wrong, and couldn't find anything. If you're referring to the extra "end" you removed in [the lastest patch](https://github.com/minetest-mods/stamina/commit/43dd5438f7fc1833ef95388413081f065cbd736a), it looks like this actually [wasn't my fault](https://github.com/minetest-mods/stamina/commit/16f284eaf22328487941b209bbc8394fa322dc48#diff-d7d74284e2e39f6c06d199c8e2bedbd0R126). I also believe I would have noticed that while testing. If not, I would appreciate if you could elaborate, so I can improve my lua coding abilities.

**Pull request closed without merging**
